BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "INGRESSOS" (
	"CODIGO"	INTEGER NOT NULL UNIQUE,
	"APRESENTACAO"	INTEGER NOT NULL UNIQUE,
	"CPF"	INTEGER NOT NULL,
	PRIMARY KEY("CODIGO"),
	FOREIGN KEY("CPF") REFERENCES "USUARIOS"("CPF"),
	FOREIGN KEY("APRESENTACAO") REFERENCES "APRENSENTACOES"("CODIGO")
);
CREATE TABLE IF NOT EXISTS "APRENSENTACOES" (
	"CODIGO"	TEXT NOT NULL UNIQUE,
	"DATA"	TEXT NOT NULL,
	"HORARIO"	TEXT NOT NULL,
	"PRECO"	TEXT NOT NULL,
	"SALA"	TEXT NOT NULL,
	"DISPONIBILIDADE"	TEXT NOT NULL,
	"EVENTO"	TEXT NOT NULL,
	FOREIGN KEY("EVENTO") REFERENCES "EVENTOS"("CODIGO"),
	PRIMARY KEY("CODIGO")
);
CREATE TABLE IF NOT EXISTS "EVENTOS" (
	"CODIGO"	TEXT NOT NULL UNIQUE,
	"NOME"	TEXT NOT NULL,
	"CIDADE"	TEXT NOT NULL,
	"ESTADO"	TEXT NOT NULL,
	"CLASSE"	TEXT NOT NULL,
	"FAIXA"	TEXT NOT NULL,
	"CPF"	TEXT NOT NULL,
	PRIMARY KEY("CODIGO"),
	FOREIGN KEY("CPF") REFERENCES "USUARIOS"("CPF")
);
CREATE TABLE IF NOT EXISTS "USUARIOS" (
	"CPF"	TEXT NOT NULL UNIQUE,
	"SENHA"	TEXT NOT NULL,
	"CARTAO"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("CPF"),
	FOREIGN KEY("CARTAO") REFERENCES "CARTOES"("NUMERO_CARTAO")
);
CREATE TABLE IF NOT EXISTS "CARTOES" (
	"NUMERO_CARTAO"	TEXT NOT NULL UNIQUE,
	"CODIGO_VERIFICADOR"	TEXT,
	"DATA_VALIDADE"	TEXT,
	PRIMARY KEY("NUMERO_CARTAO")
);
INSERT INTO "USUARIOS" VALUES ('033.444.555-66','SENHAAQUI','5438202134880191');
INSERT INTO "CARTOES" VALUES ('5438202134880191','987','09/20');
COMMIT;
